// src/app/models/event.model.ts
export interface Event {
    id?: number; // Optional because it's auto-generated by the backend
    titre: string;
    lieu: string;
    dateTime: string; // Use string for simplicity, or use Date if needed
    topic: string;
    statut: string;
  }